name: flux-docs build and check
on: pull_request
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master

  check-examples:
    name: ensure latest examples built
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Build Docs and Check Files
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          cp -R ./auto_examples /tmp/auto_examples
          flux start make html
          echo "Testing that you built the auto-examples, if this fails run flux start make html locally."
          python .github/scripts/check_diff.py /tmp/auto_examples ./auto_examples
          
  spell-and-linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: >-
          sudo apt-get update -y &&
          sudo apt-get install -y python3-pip &&
          sudo pip3 install --upgrade -r ./requirements.txt

    - name: Check Spelling
      uses: crate-ci/typos@7ad296c72fa8265059cc03d1eda562fbdfcd6df2 # v1.9.0
      with:
        files: "*.rst */*.rst */*/*.rst"
   
    - name: make linkcheck
      run: make linkcheck
